In [5]:
import numpy as np

"""Layer 1"""
bottem_sobel = np.array([
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]]
)

top_sobel = np.array([
    [1, 2, 1],
    [0, 0, 0],
    [-1, -2, -1]
])

sharpening = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
])

weighted_averaging_3x3 = np.array([
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]
])

"""Layer 2"""
robert_x = np.array([
    [1, 0],
    [0, -1]
])

robert_y = np.array([
    [0, 1],
    [-1, 0]
])

averaging_2x2 = np.array([
    [1, 1],
    [1, 1]
])

"""Layer 3"""
gaussian_5x5 = np.array([
    [1, 4, 7, 4, 1],
    [4, 16, 26, 16, 4],
    [7, 26, 41, 26, 7],
    [4, 16, 26, 16, 4],
    [1, 4, 7, 4, 1]
])

def Conv2D(img, filters, stride, padding):
    assert padding in ['same', 'valid']

    img_height, img_width, img_channels = img.shape
    filters_height, filters_width, filters_channels = filters[0].shape
    number_of_filters = len(filters)

    if padding == 'valid':
        pass  # Nothing changes

    elif padding == 'same':
        pad_height = max((img_height - 1) * stride + filters_height - img_height, 0)
        pad_width = max((img_width - 1) * stride + filters_width - img_width, 0)
        img = np.pad(img, ((0, pad_height), (0, pad_width), (0, 0)), mode='constant')
        img_height, img_width, img_channels = img.shape

    out_height = (img_height - filters_height) // stride + 1
    out_width = (img_width - filters_width) // stride + 1

    output_array = np.zeros((out_height, out_width, number_of_filters))

    for i in range(number_of_filters):
        filter_i = filters[i]

        for j in range(out_height):
            for k in range(out_width):
                slice_start_h = j * stride
                slice_end_h = slice_start_h + filters_height
                slice_start_w = k * stride
                slice_end_w = slice_start_w + filters_width

                output_array[j, k, i] = np.sum(img[slice_start_h:slice_end_h, slice_start_w:slice_end_w, :] * filter_i)

    return output_array


# Define a test case
img = np.random.randint(0, 255, (64, 64, 3))  # Example RGB image
filters = [bottem_sobel.reshape(3,3,1), top_sobel.reshape(3,3,1), sharpening.reshape(3,3,1)]
stride = 2
padding = 'valid'

# Apply the convolution operation
output = Conv2D(img, filters, stride, padding)

# Print the output
print("Output shape:", output.shape)
print(output)


Output shape: (31, 31, 3)
[[[-3.800e+01  3.800e+01 -4.660e+02]
  [-2.740e+02  2.740e+02 -1.010e+02]
  [-8.880e+02  8.880e+02  6.750e+02]
  ...
  [ 2.860e+02 -2.860e+02  7.730e+02]
  [-6.560e+02  6.560e+02  6.080e+02]
  [-1.100e+02  1.100e+02  4.800e+02]]

 [[-1.610e+02  1.610e+02 -4.000e+01]
  [-6.300e+02  6.300e+02  9.700e+02]
  [ 2.950e+02 -2.950e+02 -5.620e+02]
  ...
  [ 2.020e+02 -2.020e+02  1.400e+02]
  [ 8.130e+02 -8.130e+02 -1.590e+02]
  [-2.780e+02  2.780e+02  2.000e+00]]

 [[ 4.640e+02 -4.640e+02  7.200e+01]
  [ 6.330e+02 -6.330e+02  8.030e+02]
  [ 3.250e+02 -3.250e+02  7.800e+01]
  ...
  [ 4.610e+02 -4.610e+02  1.402e+03]
  [ 4.400e+02 -4.400e+02  1.159e+03]
  [-1.000e+00  1.000e+00  5.420e+02]]

 ...

 [[-7.490e+02  7.490e+02  1.190e+02]
  [-7.050e+02  7.050e+02 -1.270e+02]
  [ 4.110e+02 -4.110e+02  2.430e+02]
  ...
  [ 9.300e+02 -9.300e+02  3.150e+02]
  [-6.500e+01  6.500e+01  1.010e+02]
  [ 1.340e+02 -1.340e+02  3.970e+02]]

 [[-1.420e+02  1.420e+02 -1.480e+02]
  [-5.000e+

In [5]:
import soundfile as sf
import numpy as np

filename = 'noisy_tlou.wav'
data, fs = sf.read(filename, dtype='float32')
# Perform some mathematical operations on the data array
data = np.sin(data)

# Write the modified data back to a WAV file
sf.write('modified_file.wav', data, fs)


(2252004,)


In [4]:
data.shape

(2252004,)

In [ ]:
import numpy as np
from scipy.io import wavfile
from scipy.signal import butter, filtfilt

def butter_bandpass(lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    return b, a

def butter_bandpass_filter(data, lowcut, highcut, fs, order=5):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = filtfilt(b, a, data)
    return y

# filename = 'myfile.wav'
fs, data = wavfile.read(filename)

# Define the bandpass filter parameters
lowcut = 500.0
highcut = 1500.0

# Apply the bandpass filter to the data array
filtered_data = butter_bandpass_filter(data, lowcut, highcut, fs)

# Write the modified data back to a WAV file
wavfile.write('modified_file.wav', fs, filtered_data)
